/*
╔══════════════════════════════════════════════════════════════════════╗
║                     data.js — VOS DONNÉES                           ║
║                                                                      ║
║  LIVRES : remplissez le tableau BOOKS ci-dessous                     ║
║  AUTRES RESSOURCES : remplissez le tableau RESOURCES                 ║
╚══════════════════════════════════════════════════════════════════════╝

CHAMPS LIVRE :
  id          → numéro unique
  title       → titre complet du livre
  author      → auteur(s)
  desc        → résumé court (2-3 phrases)
  cat         → catégorie (ex: "Python", "Réseau", "Sécurité"...)
  license     → voir liste des licences ci-dessous
  date        → "YYYY-MM-DD" (date d'ajout)
  pages       → nombre de pages (optionnel)
  edition     → "2e édition" (optionnel)
  lang        → "Français" | "Anglais" | "Arabe" (optionnel, défaut: Français)
  cover       → chemin vers image de couverture (ex: "covers/python.jpg") — optionnel
  link_pdf    → chemin PDF local    ex: "livres/python-avance.pdf"
  link_ext    → lien externe        ex: "https://drive.google.com/..."
               (vous pouvez mettre les deux, ou un seul)
  tags        → ["tag1", "tag2"] pour la recherche
  featured    → true  pour l'afficher en vedette (optionnel)

LICENCES :
  "CC BY 4.0"           → Attribution libre
  "CC BY-NC"            → Non commercial
  "CC BY-SA"            → Partage identique
  "CC BY-ND"            → Pas de modification
  "Tous droits réservés"→ Consultation uniquement
  "Domaine public"      → Aucune restriction
*/

/* ════════════════════════════════════════
   INFORMATIONS DU SITE
   ════════════════════════════════════════ */
const SITE_INFO = {
  name:     "TechShare",
  owner:    "DIAWANE_R",
  tagline:  "Toutes mes ressources informatiques en un seul endroit",
  email:    "superrama86@gmail.com",
  github:   "https://github.com/Ramadiaw12",
  linkedin: "https://www.linkedin.com/in/ramatoulaye-diawane/",
};

/* ════════════════════════════════════════════════════════════════════
   📚 LIVRES — Remplacez les exemples par vos vrais livres
   ════════════════════════════════════════════════════════════════════
   ⚠️  Pour chaque livre :
       - Mettez les PDF dans le dossier  /livres/
       - Mettez les couvertures dans     /covers/
       - Remplissez link_pdf ET/OU link_ext
   ════════════════════════════════════════════════════════════════════ */

const BOOKS = [

  /* ══════════ PYTHON ══════════ */
  {
    id: "b1",
    title: "Python — Apprenez à programmer",
    author: "Vincent Le Goff",
    desc: "Le guide idéal pour débuter la programmation avec Python. Variables, fonctions, classes et modules expliqués pas à pas avec des exercices pratiques.",
    cat: "Python",
    license: "CC BY-NC",
    date: "2024-09-01",
    pages: 420,
    lang: "Français",
    cover: "covers/python-apprendre.jpg",
    link_pdf: "livres/Apprenez Python.pdf",
    link_ext: "",
    tags: ["python", "débutant", "programmation"],
    featured: true,
  },
  {
    id: "b2",
    title: "Python  — Techniques de pro",
    author: "Votre Nom",
    desc: "Décorateurs, générateurs, métaclasses, concurrence et optimisation. Pour les développeurs Python qui veulent passer au niveau supérieur.",
    cat: "Python",
    license: "CC BY 4.0",
    date: "2024-10-15",
    pages: 310,
    lang: "Français",
    cover: "covers/python-avance.jpg",
    link_pdf: "livres/Listes, dictionnaires, tuples et sets.pdf",
    link_ext: "",
    tags: ["python", "avancé", "optimisation"],
    featured: true,
  },
  {
    id: "b3",
    title: "Automatisation avec Python",
    author: "Votre Nom",
    desc: "Scripts d'automatisation, manipulation de fichiers, scraping web et interactions avec les APIs. Gagnez du temps en automatisant vos tâches répétitives.",
    cat: "Python",
    license: "CC BY 4.0",
    date: "2024-11-20",
    pages: 280,
    lang: "Français",
    cover: "covers/python-auto.jpg",
    link_pdf: "livres/Python en Bref.pdf",
    link_ext: "",
    tags: ["python", "automatisation", "scripting"],
  },

  /* ══════════ ALGORITHMES ══════════ */
  {
    id: "b4",
    title: "Algorithmes et structures de données",
    author: "Votre Nom",
    desc: "Les algorithmes fondamentaux : tri, recherche, graphes, arbres. Analyse de complexité et implémentations en Python et C++.",
    cat: "Algorithmique",
    license: "CC BY-NC",
    date: "2024-08-05",
    pages: 380,
    lang: "Français",
    cover: "covers/algos.jpg",
    link_pdf: "livres/python_data_structure_tutorial.pdf",
    link_ext: "",
    tags: ["algorithmes", "structures de données", "complexité"],
    featured: true,
  },
  {
    id: "b5",
    title: "Introduction à la théorie des graphes",
    author: "Votre Nom",
    desc: "Concepts fondamentaux des graphes appliqués à l'informatique : parcours, plus courts chemins, arbres couvrants et réseaux de flots.",
    cat: "Algorithmique",
    license: "CC BY-SA",
    date: "2024-07-12",
    pages: 220,
    lang: "Français",
    cover: "covers/graphes.jpg",
    link_pdf: "livres/Cours-Classes-Prépas-d_Ing.pdf",
    link_ext: "",
    tags: ["graphes", "algorithmes", "mathématiques"],
  },

  /* ══════════ LINUX / SYSTÈMES ══════════ */
  {
    id: "b6",
    title: "Linux — Administration système",
    author: "Votre Nom",
    desc: "Installation, configuration, gestion des utilisateurs, services systemd, cron, et maintenance d'un serveur Linux en production.",
    cat: "Linux",
    license: "CC BY 4.0",
    date: "2025-01-10",
    pages: 460,
    lang: "Français",
    cover: "covers/linux-admin.jpg",
    link_pdf: "livres/Pro Linux System Administration.pdf",
    link_ext: "",
    tags: ["linux", "administration", "serveur", "systemd"],
    featured: true,
  },
  {
    id: "b7",
    title: "Bash — Scripts shell avancés",
    author: "Votre Nom",
    desc: "Maîtriser Bash pour l'automatisation : variables, boucles, fonctions, expressions régulières et gestion des processus.",
    cat: "Linux",
    license: "CC BY 4.0",
    date: "2024-12-03",
    pages: 195,
    lang: "Français",
    cover: "covers/bash.jpg",
    link_pdf: "livres/Practical Linux Security Cookbook.pdf",
    link_ext: "",
    tags: ["bash", "shell", "linux", "scripting"],
  },
  {
    id: "b8",
    title: "Bash - Scripts shell - Commande line interface",
    author: "Votre Nom",
    desc: "Maîtrisé Linux pour la programmation.",
    cat: "Linux",
    license: "CC BY 4.0",
    date: "2024-12-03",
    pages: 195,
    lang: "Français",
    cover: "covers/bash.jpg",
    link_pdf: "livres/Linux Sound Programming.pdf",
    link_ext: "",
    tags: ["bash", "shell", "linux", "scripting"],
  },
  {
    id: "b9",
    title: "Systèmes d'exploitation — Concepts fondamentaux",
    author: "Votre Nom",
    desc: "Processus, threads, mémoire virtuelle, système de fichiers et ordonnancement. Cours universitaire complet avec exercices corrigés.",
    cat: "Linux",
    license: "CC BY-NC",
    date: "2024-06-20",
    pages: 350,
    lang: "Français",
    cover: "covers/os.jpg",
    link_pdf: "livres/Installation, Storage and Compute with Windows Server 2016.pdf",
    link_ext: "",
    tags: ["OS", "processus", "mémoire", "université"],
  },

  /* ══════════ RÉSEAUX ══════════ */
  {
    id: "b10",
    title: "Réseaux informatiques — TCP/IP en pratique",
    author: "Votre Nom",
    desc: "Modèle OSI, protocoles TCP/IP, routage, DNS, DHCP et configuration réseau. Des bases théoriques aux manipulations pratiques sous Linux.",
    cat: "Réseau",
    license: "CC BY-NC",
    date: "2024-05-14",
    pages: 400,
    lang: "Français",
    cover: "covers/reseaux.jpg",
    link_pdf: "livres/reseaux-tcp-ip.pdf",
    link_ext: "",
    tags: ["réseau", "TCP/IP", "DNS", "routage"],
    featured: true,
  },
  {
    id: "b11",
    title: "WiFi et sécurité sans fil",
    author: "Votre Nom",
    desc: "Protocoles 802.11, WPA2/WPA3, attaques courantes sur le WiFi et méthodes de sécurisation des réseaux sans fil.",
    cat: "Réseau",
    license: "CC BY-NC",
    date: "2024-09-28",
    pages: 180,
    lang: "Français",
    cover: "covers/wifi.jpg",
    link_pdf: "livres/wifi-securite.pdf",
    link_ext: "",
    tags: ["wifi", "sécurité", "802.11", "WPA"],
  },

  /* ══════════ CYBERSÉCURITÉ ══════════ */
  {
    id: "b12",
    title: "Cybersécurité — Guide du pentester",
    author: "Votre Nom",
    desc: "Méthodologie de tests d'intrusion, reconnaissance, exploitation et rapport. Outils Kali Linux, Metasploit et Burp Suite présentés en détail.",
    cat: "Cybersécurité",
    license: "Tous droits réservés",
    date: "2025-02-01",
    pages: 520,
    lang: "Français",
    cover: "covers/pentest.jpg",
    link_pdf: "",
    link_ext: "https://drive.google.com/drive/u/0/folders/179D_slEOLXWOTeFdmRrMkdV8C4DSLdYT?s=08",
    tags: ["pentest", "sécurité", "kali", "metasploit"],
    featured: true,
  },
  {
    id: "b13",
    title: "Cryptographie appliquée",
    author: "Votre Nom",
    desc: "Chiffrement symétrique et asymétrique, hachage, signatures numériques, PKI et TLS. Théorie et implémentation en Python.",
    cat: "Cybersécurité",
    license: "CC BY-NC",
    date: "2024-11-05",
    pages: 290,
    lang: "Français",
    cover: "covers/crypto.jpg",
    link_pdf: "livres/cryptographie-appliquee.pdf",
    link_ext: "",
    tags: ["cryptographie", "TLS", "RSA", "AES"],
  },
  {
    id: "b14",
    title: "Sécurité des applications web",
    author: "Votre Nom",
    desc: "OWASP Top 10, XSS, injection SQL, CSRF, gestion des sessions et sécurisation des APIs REST. Avec laboratoires pratiques.",
    cat: "Cybersécurité",
    license: "CC BY-NC",
    date: "2024-10-22",
    pages: 340,
    lang: "Français",
    cover: "covers/secu-web.jpg",
    link_pdf: "",
    link_ext: "https://drive.google.com/drive/u/0/folders/1DqvFPxC3ROZgRndVYsfpX7C7Nqx1CnmL",
    tags: ["web", "OWASP", "XSS", "injection SQL"],
  },
  {
    id: "b15",
    title: "Dark web",
    author: "Votre Nom",
    desc: "Dark web Monitoring tools you.",
    cat: "Cybersécurité",
    license: "Tous droits réservés",
    date: "2025-02-01",
    pages: 520,
    lang: "Français",
    cover: "covers/pentest.jpg",
    link_pdf: "livres/Dark web.pdf",
    link_ext: "",
    tags: ["pentest", "sécurité", "kali", "metasploit"],
    featured: true,
  },

  /* ══════════ BASES DE DONNÉES ══════════ */
  {
    id: "b16",
    title: "SQL — Du débutant à l'expert",
    author: "Votre Nom",
    desc: "Requêtes SELECT, jointures complexes, sous-requêtes, transactions, procédures stockées et optimisation des performances.",
    cat: "Bases de données",
    license: "CC BY 4.0",
    date: "2024-08-18",
    pages: 310,
    lang: "Français",
    cover: "covers/sql.jpg",
    link_pdf: "livres/sql-complet.pdf",
    link_ext: "",
    tags: ["SQL", "base de données", "requêtes"],
    featured: true,
  },
  {
    id: "b17",
    title: "PostgreSQL — Administration avancée",
    author: "Votre Nom",
    desc: "Installation, configuration, réplication, sauvegardes, monitoring et tuning de performances pour PostgreSQL en production.",
    cat: "Bases de données",
    license: "CC BY 4.0",
    date: "2025-01-25",
    pages: 380,
    lang: "Français",
    cover: "covers/postgresql.jpg",
    link_pdf: "livres/postgresql-admin.pdf",
    link_ext: "",
    tags: ["PostgreSQL", "administration", "réplication"],
  },
  {
    id: "b18",
    title: "NoSQL — MongoDB et Redis",
    author: "Votre Nom",
    desc: "Modélisation de données non relationnelles, requêtes MongoDB, agrégations et cache distribué avec Redis.",
    cat: "Bases de données",
    license: "CC BY-NC",
    date: "2024-07-30",
    pages: 250,
    lang: "Français",
    cover: "covers/nosql.jpg",
    link_pdf: "livres/nosql-mongodb-redis.pdf",
    link_ext: "",
    tags: ["NoSQL", "MongoDB", "Redis", "base de données"],
  },

  /* ══════════ DÉVELOPPEMENT WEB ══════════ */
  {
    id: "b18",
    title: "HTML & CSS — Fondamentaux du web",
    author: "Votre Nom",
    desc: "Structure sémantique HTML5, mise en page CSS3, Flexbox, Grid et responsive design. Avec 10 projets pratiques.",
    cat: "Web",
    license: "CC BY 4.0",
    date: "2024-04-10",
    pages: 360,
    lang: "Français",
    cover: "covers/html-css.jpg",
    link_pdf: "livres/html-css.pdf",
    link_ext: "",
    tags: ["HTML", "CSS", "web", "responsive"],
  },
  {
    id: "b20",
    title: "JavaScript — Moderne et pratique",
    author: "Votre Nom",
    desc: "ES6+, Promises, async/await, modules, DOM et manipulation d'APIs REST. Du vanilla JS au développement moderne.",
    cat: "Web",
    license: "CC BY 4.0",
    date: "2024-05-20",
    pages: 420,
    lang: "Français",
    cover: "covers/javascript.jpg",
    link_pdf: "livres/javascript-moderne.pdf",
    link_ext: "",
    tags: ["JavaScript", "ES6", "async", "DOM"],
    featured: true,
  },
  {
    id: "b21",
    title: "APIs REST — Conception et développement",
    author: "Votre Nom",
    desc: "Design d'APIs RESTful, authentification JWT, documentation Swagger, versioning et bonnes pratiques de sécurité.",
    cat: "Web",
    license: "CC BY-NC",
    date: "2024-09-15",
    pages: 270,
    lang: "Français",
    cover: "covers/api-rest.jpg",
    link_pdf: "",
    link_ext: "https://drive.google.com/drive/u/0/folders/1p5jc-bYodKcfgLX8UcCf4krctg0xzoFg",
    tags: ["API", "REST", "JWT", "Swagger"],
  },

  /* ══════════ DEVOPS / CLOUD ══════════ */
  {
    id: "b22",
    title: "Docker — De zéro à la production",
    author: "Votre Nom",
    desc: "Images, conteneurs, volumes, réseaux Docker et Docker Compose. Déploiement d'applications multi-services en production.",
    cat: "DevOps",
    license: "CC BY 4.0",
    date: "2025-01-08",
    pages: 300,
    lang: "Français",
    cover: "covers/docker.jpg",
    link_pdf: "livres/docker-production.pdf",
    link_ext: "",
    tags: ["Docker", "conteneurs", "DevOps"],
    featured: true,
  },
  {
    id: "b23",
    title: "Kubernetes — Orchestration de conteneurs",
    author: "Votre Nom",
    desc: "Pods, Deployments, Services, Ingress, ConfigMaps et Secrets. Gestion d'un cluster Kubernetes de A à Z.",
    cat: "DevOps",
    license: "CC BY-NC",
    date: "2025-02-14",
    pages: 450,
    lang: "Français",
    cover: "covers/kubernetes.jpg",
    link_pdf: "",
    link_ext: "https://drive.google.com/drive/u/0/folders/16kF3Xn2DXC0HQLwXi2fGD4YRaet4BrBu",
    tags: ["Kubernetes", "K8s", "orchestration", "cloud"],
  },
  {
    id: "b24",
    title: "CI/CD avec GitHub Actions",
    author: "Votre Nom",
    desc: "Pipelines d'intégration et déploiement continus, tests automatisés, déploiement sur cloud et gestion des secrets.",
    cat: "DevOps",
    license: "CC BY 4.0",
    date: "2024-12-20",
    pages: 220,
    lang: "Français",
    cover: "covers/cicd.jpg",
    link_pdf: "livres/cicd-github-actions.pdf",
    link_ext: "",
    tags: ["CI/CD", "GitHub Actions", "DevOps", "automatisation"],
  },

  /* ══════════ INTELLIGENCE ARTIFICIELLE ══════════ */
  {
    id: "b25",
    title: "Advanced Deep Learning",
    author: "Votre Nom",
    desc: "Régression, classification, clustering, évaluation de modèles et scikit-learn. Du théorème de Bayes aux forêts aléatoires.",
    cat: "Intelligence Artificielle",
    license: "CC BY-NC",
    date: "2024-11-30",
    pages: 490,
    lang: "Français",
    cover: "covers/ml.jpg",
    link_pdf: "livres/mdl.pdf",
    link_ext: "",
    tags: ["machine learning", "IA", "scikit-learn", "classification"],
    featured: true,
  },
  {
    id: "b26",
    title: "Deep Learning avec TensorFlow et Keras",
    author: "Votre Nom",
    desc: "Réseaux de neurones, CNN, RNN, LSTM et Transformers. Projets de vision par ordinateur et traitement du langage naturel.",
    cat: "Intelligence Artificielle",
    license: "CC BY-NC",
    date: "2025-01-20",
    pages: 560,
    lang: "Français",
    cover: "covers/deeplearning.jpg",
    link_pdf: "livres/deep-learning.pdf",
    link_ext: "",
    tags: ["deep learning", "TensorFlow", "Keras", "CNN", "NLP"],
  },
  {
    id: "b27",
    title: "Traitement du langage naturel (NLP)",
    author: "Votre Nom",
    desc: "Tokenisation, embeddings, modèles Transformer, BERT et GPT. Applications pratiques : classification de texte, résumé automatique.",
    cat: "Intelligence Artificielle",
    license: "CC BY-NC",
    date: "2025-02-28",
    pages: 380,
    lang: "Français",
    cover: "covers/nlp.jpg",
    link_pdf: "livres/nlp.pdf",
    link_ext: "",
    tags: ["NLP", "BERT", "Transformers", "langage naturel"],
  },

  /* ══════════ MATHÉMATIQUES ══════════ */
  {
    id: "b28",
    title: "Mathématiques pour l'informatique",
    author: "Votre Nom",
    desc: "Logique, ensembles, combinatoire, probabilités et algèbre linéaire. Bases mathématiques indispensables au développeur.",
    cat: "Mathématiques",
    license: "CC BY-SA",
    date: "2024-03-15",
    pages: 420,
    lang: "Français",
    cover: "covers/maths.jpg",
    link_pdf: "",
    link_ext: "https://drive.google.com/drive/u/0/folders/1CgN7DE3pNRNh_4BA_zrrMLqWz6KquwuD",
    tags: ["Big data", "Advanced Deep Learning", "Artificial Intelligence", "algèbre"],
  },
  {
    id: "b29",
    title: "Algèbre linéaire pour le Machine Learning",
    author: "Votre Nom",
    desc: "Vecteurs, matrices, valeurs propres, décomposition SVD et applications directes aux algorithmes de ML.",
    cat: "Mathématiques",
    license: "CC BY-SA",
    date: "2024-04-22",
    pages: 250,
    lang: "Français",
    cover: "covers/algebre.jpg",
    link_pdf: "livres/algebre-lineaire-ml.pdf",
    link_ext: "",
    tags: ["algèbre", "matrices", "ML", "SVD"],
  },

  /* ══════════ MOBILE ══════════ */
  {
    id: "b30",
    title: "Développement Android avec Kotlin",
    author: "Votre Nom",
    desc: "Architecture MVVM, Jetpack Compose, Room, Retrofit et publication sur le Play Store. Développement Android moderne.",
    cat: "Mobile",
    license: "CC BY-NC",
    date: "2024-06-10",
    pages: 430,
    lang: "Français",
    cover: "covers/android.jpg",
    link_pdf: "livres/android-kotlin.pdf",
    link_ext: "",
    tags: ["Android", "Kotlin", "Jetpack Compose", "mobile"],
  },
  {
    id: "b31",
    title: "Flutter — Applications cross-platform",
    author: "Votre Nom",
    desc: "Widgets, navigation, gestion d'état avec Riverpod, accès aux APIs et déploiement iOS/Android depuis une seule base de code.",
    cat: "Mobile",
    license: "CC BY 4.0",
    date: "2024-08-25",
    pages: 370,
    lang: "Français",
    cover: "covers/flutter.jpg",
    link_pdf: "livres/flutter.pdf",
    link_ext: "",
    tags: ["Flutter", "Dart", "cross-platform", "mobile"],
  },

  /* ══════════ LIENS EXTERNES (exemples) ══════════ */
  {
    id: "b32",
    title: "The Linux Command Line (William Shotts)",
    author: "William E. Shotts Jr.",
    desc: "Référence complète sur la ligne de commande Linux. Disponible gratuitement en ligne sous licence Creative Commons.",
    cat: "Linux",
    license: "CC BY-NC-SA",
    date: "2024-01-01",
    pages: 540,
    lang: "Anglais",
    cover: "covers/linux-cli.jpg",
    link_pdf: "",
    link_ext: "https://linuxcommand.org/tlcl.php",
    tags: ["linux", "terminal", "bash", "commandes"],
  },
  {
    id: "b33",
    title: "Pro Git (Scott Chacon)",
    author: "Scott Chacon & Ben Straub",
    desc: "Le livre de référence sur Git, disponible gratuitement. Couvre tous les aspects de Git du débutant à l'expert.",
    cat: "DevOps",
    license: "CC BY-NC-SA",
    date: "2024-01-01",
    pages: 440,
    lang: "Français",
    cover: "covers/progit.jpg",
    link_pdf: "",
    link_ext: "https://git-scm.com/book/fr/v2",
    tags: ["git", "versionning", "GitHub"],
  },
  {
    id: "b34",
    title: "Eloquent JavaScript (Marijn Haverbeke)",
    author: "Marijn Haverbeke",
    desc: "Introduction approfondie à JavaScript et à la programmation. Disponible gratuitement en ligne sous licence CC.",
    cat: "Web",
    license: "CC BY-NC",
    date: "2024-01-01",
    pages: 472,
    lang: "Anglais",
    cover: "covers/eloquent-js.jpg",
    link_pdf: "",
    link_ext: "https://eloquentjavascript.net",
    tags: ["JavaScript", "programmation", "débutant"],
  },

];

/* ════════════════════════════════════════════════════════════════
   AUTRES RESSOURCES (cours, docs, outils, articles...)
   ════════════════════════════════════════════════════════════════ */

const RESOURCES = [
  {
    id: 1,
    title: "Introduction à Python — cours complet",
    desc: "Cours complet pour apprendre Python de zéro. Couvre les bases, la POO, les fichiers et les modules standard. Exercices corrigés inclus.",
    type: "Cours",
    cat: "Python",
    license: "CC BY 4.0",
    date: "2024-11-15",
    link: "fichiers/python-intro.pdf",
    tags: ["python", "débutant", "programmation"],
  },
  {
    id: 2,
    title: "Guide Git & GitHub — workflows professionnels",
    desc: "Documentation complète sur la gestion de versions avec Git. Branches, pull requests, rebasing et intégration CI/CD.",
    type: "Documentation",
    cat: "DevOps",
    license: "MIT",
    date: "2024-10-03",
    link: "https://votresite.com/git-guide",
    tags: ["git", "github", "versionning"],
  },
  {
    id: 3,
    title: "Algorithmes de tri — visualisation & explications",
    desc: "Article illustré sur les principaux algorithmes de tri avec complexité et cas d'usage.",
    type: "Article",
    cat: "Algorithmique",
    license: "CC BY-NC",
    date: "2024-09-20",
    link: "articles/tri-algorithmes.html",
    tags: ["algorithme", "tri", "complexité"],
  },
  {
    id: 4,
    title: "Script Python — nettoyage automatique de fichiers",
    desc: "Outil en ligne de commande pour organiser et nettoyer un répertoire selon les extensions. Entièrement documenté.",
    type: "Outil",
    cat: "Python",
    license: "GPL v3",
    date: "2025-01-08",
    link: "https://github.com/votreprofil/file-cleaner",
    tags: ["script", "automatisation", "cli"],
  },
  {
    id: 5,
    title: "Bases de données SQL — guide pratique",
    desc: "Requêtes, jointures, sous-requêtes, indexation et optimisation expliquées avec des exercices pratiques sur PostgreSQL.",
    type: "Documentation",
    cat: "Bases de données",
    license: "CC BY 4.0",
    date: "2025-02-14",
    link: "fichiers/sql-guide.pdf",
    tags: ["sql", "postgresql", "database"],
  },
  /* Ajoutez d'autres ressources ici... */
];

/* ════════════════════════════════════════
   ICÔNES DES CATÉGORIES
   ════════════════════════════════════════ */
const CATEGORY_ICONS = {
  "Python":                    "ti-brand-python",
  "JavaScript":                "ti-brand-javascript",
  "DevOps":                    "ti-server",
  "Linux":                     "ti-brand-ubuntu",
  "Algorithmique":             "ti-chart-dots",
  "Bases de données":          "ti-database",
  "Cybersécurité":             "ti-shield-lock",
  "Intelligence Artificielle": "ti-brain",
  "Réseau":                    "ti-network",
  "Web":                       "ti-world",
  "Mobile":                    "ti-device-mobile",
  "DevOps":                    "ti-server",
  "Mathématiques":             "ti-math-function",
  "Cloud":                     "ti-cloud",
  "Autre":                     "ti-folder",
};

/* ════════════════════════════════════════
   LICENCES
   ════════════════════════════════════════ */
const LICENSE_INFO = {
  "CC BY 4.0":           { cls: "lic-open",    terms: "Usage libre avec attribution obligatoire." },
  "CC BY-NC":            { cls: "lic-nc",      terms: "Usage non commercial. Attribution obligatoire." },
  "CC BY-SA":            { cls: "lic-cc",      terms: "Redistribution sous la même licence avec attribution." },
  "CC BY-ND":            { cls: "lic-cc",      terms: "Redistribution permise sans modification, avec attribution." },
  "CC BY-NC-SA":         { cls: "lic-nc",      terms: "Non commercial, partage identique." },
  "MIT":                 { cls: "lic-open",    terms: "Usage libre y compris commercial. Conservez la notice." },
  "GPL v3":              { cls: "lic-open",    terms: "Logiciel libre. Modifications à redistribuer sous GPL v3." },
  "Apache 2.0":          { cls: "lic-open",    terms: "Usage libre et commercial. Conservez la notice Apache." },
  "Domaine public":      { cls: "lic-open",    terms: "Aucune restriction. Usage totalement libre." },
  "Tous droits réservés":{ cls: "lic-reserve", terms: "Consultation uniquement. Reproduction interdite sans accord." },
};